name: ci software-website

on: 
  push:
    branches: [development, master]
    paths:
      - "!README.md"
      
  pull_request:
    branches: [development, master]
    paths:
      - "!README.md"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      HOME: '.'
    steps:
      - name: clone into repo
        uses: actions/checkout@v2

      - name: install hugo
        run: sudo apt-get install hugo

      - name: setup hugo
        run: hugo -s src -d ../target
      
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          # disable caching since it causes problems on post Run:
          # Post job cleanup.
          # /opt/hostedtoolcache/node/12.22.9/x64/bin/npm config get cache
          # /home/runner/work/software-website/software-website/.npm
          # Error: Cache folder path is retrieved for npm but doesn't exist on disk: /home/runner/work/software-website/software-website/.npm

          # cache: 'npm'
          # cache-dependency-path: mail-client/package.json
      - name: mail client
        run : npm install
        working-directory: mail-client
